# Generated by Django 2.1.5 on 2020-04-04 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_auto_20200404_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='url',
            field=models.CharField(default='hoihioh', max_length=200),
        ),
    ]
