# Generated by Django 2.1.5 on 2020-04-04 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_auto_20200404_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='url',
            field=models.TextField(default='hoihioh'),
        ),
    ]
