# Generated by Django 2.1.5 on 2020-04-04 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_auto_20200404_1813'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='url',
        ),
    ]
